feat: setting up the router & add Pokemon Details pages
NoahMi76/my-pokedex pull request #3
Opened 2023-05-26 15:09 UTC by NoahMi76

2023-05-30 07:37 UTC, Philippe-Tic requested changes

2023-05-30 07:37 UTC, Philippe-Tic commented on src/components/PokemonDetails.jsx
> +    const fetchPokemonDetails = async () => {
Tu pourrais rajouter un loader là dessus ! ça aiderait à donner du feedback sur le fait que ça charge a l'utilisateur

2023-05-30 07:37 UTC, Philippe-Tic commented on src/components/PokemonButton.jsx
>  const PokemonButton = ({ onClick }) => {
Ce composant là peut être plus "réutilisable" et générique en ayant juste un composant Button qui prendra en props le label (sous forme de children), et la className avec une certaine par défaut

2023-05-30 07:37 UTC, Philippe-Tic commented on src/components/PokemonDetails.jsx
> +        <PokemonButton ></PokemonButton>
Tu peux utilisé la notation <PokemonButton /> (et d'ailleurs il sert pas à grand chose tel quel :p )

2023-05-30 07:37 UTC, Philippe-Tic commented on src/components/PokemonDetails.css
> +    font-size: 36px;
On utiilise des rem plutôt que des px dans les projets, le pixel est quasi-banni (utilisé seulement sur des attribut type border). cela permet un meilleur responsive et une meilleur accessibilité

2023-05-30 07:38 UTC, Philippe-Tic commented
Prends l'habitude d'écrire dans tes PR/MR une description de de ce que tu as fait et aussi une partie "comment tester". On utilise un template comme ça en général :

## Ce qui a été fait 
- 
-
-

## Comment tester
-
-
-

2023-06-01 08:29 UTC, enzobillisPG commented on src/components/PokemonDetails.jsx
> +        setIsLoading(false);
De manière général on ajoute le setIsLoading(false) dans le finally du try catch afin qu'il soit toujours fait. Là si tu as une erreur et que tu passes dans le catch, ca restera en chargement ;)

2023-06-01 08:29 UTC, enzobillisPG commented on src/components/PokemonDetails.jsx
> +  if (!pokemon) {
Dans cette condition je te conseille de mettre !pokemon && !isLoading ce qui veut dire que si ce n'est plus en chargement et qu'il y a toujours pas de pokemon c'est qu'il y a une erreur

2023-06-01 15:16 UTC, merged